-- Production history marker for operator_advisor_remediation.
-- This migration was applied through the verified Main launch-hardening rollout.
-- The live schema and customer data are retained; no replay is required here.
