create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  notification_type text not null default 'appointment_reminder',
  sent_at timestamptz not null default now(),
  unique (user_id, booking_id, notification_type)
);

create index if not exists push_subscriptions_workspace_idx on public.push_subscriptions(workspace_id);
create index if not exists notification_deliveries_booking_idx on public.notification_deliveries(booking_id);

alter table public.push_subscriptions enable row level security;
alter table public.notification_deliveries enable row level security;

create policy "Members manage their push subscriptions" on public.push_subscriptions
for all to authenticated
using (user_id = (select auth.uid()) and private.can_read_workspace(workspace_id) and private.has_feature(workspace_id, 'mobile_app'))
with check (user_id = (select auth.uid()) and private.can_read_workspace(workspace_id) and private.has_feature(workspace_id, 'mobile_app'));

create policy "Members view their notification deliveries" on public.notification_deliveries
for select to authenticated
using (user_id = (select auth.uid()) and private.can_read_workspace(workspace_id));

grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant select on public.notification_deliveries to authenticated;
grant usage, select on sequence public.notification_deliveries_id_seq to authenticated;

create trigger set_push_subscriptions_updated_at before update on public.push_subscriptions
for each row execute function private.touch_updated_at();
